import { ArrowRight, BarChart3, Brain, DollarSign, Target, Zap } from "lucide-react";
import { SearchInput } from "./SearchInput";

interface HeroSectionProps {
  onSearch: (query: string) => void;
  isLoading: boolean;
}

export function HeroSection({ onSearch, isLoading }: HeroSectionProps) {
  const features = [
    { icon: BarChart3, label: "BSR Analysis" },
    { icon: Brain, label: "AI Insights" },
    { icon: DollarSign, label: "Profit Forecast" },
    { icon: Target, label: "Opportunity Mapping" },
  ];

  return (
    <section className="relative overflow-x-hidden">
      {/* Background Effects */}
      <div className="absolute inset-0 bg-grid-pattern bg-grid opacity-30" />
      <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-primary/20 rounded-full blur-3xl animate-pulse-slow" />
      <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-gold/10 rounded-full blur-3xl animate-pulse-slow delay-1000" />

      <div className="container relative py-24 lg:py-32">
        <div className="text-center max-w-4xl mx-auto">
          {/* Badge */}
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 border border-primary/20 mb-6 animate-fade-in">
            <Zap className="w-4 h-4 text-primary" />
            <span className="text-sm font-medium text-primary">
              AI-Powered Publishing Intelligence
            </span>
          </div>

          {/* Headline */}
          <h1 className="text-4xl md:text-6xl lg:text-7xl font-bold mb-6 animate-slide-up">
            Stop Guessing.
            <br />
            <span className="gradient-text">Start Publishing</span>
            <br />
            Where Money Lives.
          </h1>

          {/* Subheadline */}
          <p
            className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto mb-10 animate-slide-up"
            style={{ animationDelay: "100ms" }}
          >
            Replace weeks of manual research with instant market intelligence.
            Discover exactly which Amazon KDP niches are profitable{" "}
            <span className="text-foreground font-medium">
              before you invest a single dollar
            </span>
            .
          </p>

          {/* Search Input */}
          <div
            className="animate-slide-up mb-12"
            style={{ animationDelay: "200ms" }}
          >
            <SearchInput onSearch={onSearch} isLoading={isLoading} />
          </div>

          {/* Feature Pills */}
          <div
            className="flex flex-wrap justify-center gap-4 animate-fade-in"
            style={{ animationDelay: "400ms" }}
          >
            {features.map((feature, i) => {
              const Icon = feature.icon;
              return (
                <div
                  key={i}
                  className="flex items-center gap-2 px-4 py-2 rounded-lg bg-card/50 border border-border/50"
                >
                  <Icon className="w-4 h-4 text-primary" />
                  <span className="text-sm text-muted-foreground">
                    {feature.label}
                  </span>
                </div>
              );
            })}
          </div>

          {/* Trust Indicators */}
          <div
            className="mt-16 flex flex-col items-center gap-4 animate-fade-in"
            style={{ animationDelay: "600ms" }}
          >
            <p className="text-xs uppercase tracking-widest text-muted-foreground">
              Trusted by 10,000+ self-publishers
            </p>
            <div className="flex items-center gap-8 text-muted-foreground/50">
              <span className="text-2xl font-bold">$2.4M+</span>
              <span className="text-sm">Revenue generated by users</span>
            </div>
          </div>
        </div>
      </div>

      {/* Scroll Indicator */}
      <div className="absolute bottom-8 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2 text-muted-foreground animate-bounce">
        <span className="text-xs">Scroll to see results</span>
        <ArrowRight className="w-4 h-4 rotate-90" />
      </div>
    </section>
  );
}
